//here i will create the notication model which will store the user notification
//Notification ID
//User ID -> Reference to the User model 
//Notification Type -> Trade alert , MarketNews, AI Signal
//Message Content 
//Read Status -> Read or unread 
//Time Stamp -> Auto generated by The Data base