//here i will create the order model
//Order ID -> auto generated by the MongoDB database
//User ID -> reference to the User model 
//Stock ID or symbol or name -> 
//Order Type -> (Market, Limit, Stop-loss, Bracket Orders )
//Trade Type -> Buy or sell
//Quantity -> 
//Order Price 
//Stop loss or Take profit levels 
//Status -> (Pending, Executed, Rejected, Cancelled)
//Execution time stamp will created by the mongoDB database 
