//Here i will create the Trasection model to store the transaction which was done by the user to show the transaction
//Transaction ID -> Auto Created by the Mongo DB databas 
//User ID -> Reference to the User model
//Trasaction type -> (Deposit, Withdrawal, Trade Execution)
//Amount 
//Payment Method -> Bank Transfer, UPI, Credit card, etc
//Status -> successfull, pending, failed 
//Time Stamp -> will be auto generated by the mongoDB database 

